### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Luka967** [Luka967/Ogar#1]
approx. 95% of edits are done, all that is left:
- [x] tweak collision a bit
- [x] update gamemodes
- [x] virus feeding
- [ ] bounciness (kinda works)
- [x] update bots

bugs created:
- [x] make playercells faster
- [x] fix ejected cells' ejecting movement
- [x] investigate playerTracker's visiblity range (it's just perfect!)
- ??? there's probably more
